services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: axum_poc
      POSTGRES_PASSWORD: KEPdBtU4iP3LzYZEU48EMq
      POSTGRES_USER: poc_user
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U poc_user -d axum_poc" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    network_mode: host
